export const parts = [
  {
    code: "ST-1326",
    name: "TP-HF DELUXE SILVER (TP :- Tail Panel)",
    qty: 3,
    mrp: 530,
    part: "TP",
  },
  {
    code: "ST-1326-A",
    name: "TP-HF DELUXE 3D 2015 (BK-RED) (TP :- Tail Panel)",
    qty: 3,
    mrp: 600,
    part: "TP",
  },
  {
    code: "ST-1326-B",
    name: "TP-HF DELUXE 3D 2015 (BK-BLUE) (TP :- Tail Panel)",
    qty: 3,
    mrp: 600,
    part: "TP",
  },
  {
    code: "ST-1326-C",
    name: "TP-HF DELUXE 3D 2015 (BK-PURPLE) (TP :- Tail Panel)",
    qty: 3,
    mrp: 600,
    part: "TP",
  },
  {
    code: "ST-1326-D",
    name: "TP-HF DELUXE 3D 2015 RED (TP :- Tail Panel)",
    qty: 3,
    mrp: 600,
    part: "TP",
  },
  {
    code: "ST-1326-E",
    name: "TP-HF DELUXE 3D 2015 SILVER (TP :- Tail Panel)",
    qty: 3,
    mrp: 600,
    part: "TP",
  },
  {
    code: "ST-1326-E-1",
    name: "TP-HF DELUXE 3D 2015 ECO GREEN (TP :- Tail Panel)",
    qty: 3,
    mrp: 600,
    part: "TP",
  },
  {
    code: "ST-1326-E-2",
    name: "TP-HF DELUXE 3D 2015 W.RED (TP :- Tail Panel)",
    qty: 3,
    mrp: 600,
    part: "TP",
  },
  {
    code: "ST-1326-F",
    name: "TP-HF DELUXE  BS-4 (BK-RED) (TP :- Tail Panel)",
    qty: 3,
    mrp: 620,
    part: "TP",
  },
  {
    code: "ST-1326-G",
    name: "TP-HF DELUXE  BS-4 (BK-PURPLE) (TP :- Tail Panel)",
    qty: 3,
    mrp: 620,
    part: "TP",
  },
  {
    code: "ST-1326-H",
    name: "TP-HF DELUXE  BS-4 (BK-GRAY) (TP :- Tail Panel)",
    qty: 3,
    mrp: 620,
    part: "TP",
  },
  {
    code: "ST-1326-I",
    name: "TP-HF DELUXE  BS-4 (RED-ORANGE) (TP :- Tail Panel)",
    qty: 3,
    mrp: 620,
    part: "TP",
  },
  {
    code: "ST-1326-J",
    name: "TP-HF DELUXE  BS-4 GREY (TP :- Tail Panel)",
    qty: 3,
    mrp: 620,
    part: "TP",
  },
  {
    code: "ST-1320-A",
    name: "TP-HF-DELUXE BS6 GREY (TP :- Tail Panel)",
    qty: 3,
    mrp: 530,
    part: "TP",
  },
  {
    code: "ST-1320-B",
    name: "TP-HF-DELUXE BS6 (BK-GREY) (TP :- Tail Panel)",
    qty: 3,
    mrp: 530,
    part: "TP",
  },
  {
    code: "ST-1320-C",
    name: "TP-HF-DELUXE BS6 (BK-RED) (TP :- Tail Panel)",
    qty: 3,
    mrp: 530,
    part: "TP",
  },
  {
    code: "ST-1320-D",
    name: "TP-HF-DELUXE BS6 (BK-PURPLE) (TP :- Tail Panel)",
    qty: 3,
    mrp: 530,
    part: "TP",
  },
  {
    code: "ST-1320-E",
    name: "TP-HF-DELUXE BS6 BLUE (TP :- Tail Panel)",
    qty: 3,
    mrp: 530,
    part: "TP",
  },
  {
    code: "ST-1320-F",
    name: "TP-HF DELUXE BS6 (BK-NEXUS BLUE) (TP :- Tail Panel)",
    qty: 3,
    mrp: 530,
    part: "TP",
  },
  {
    code: "ST-1375",
    name: "TP-SPLENDOR I-SMART TAIL BLACK FOR S.RED BIKE (TP :- Tail Panel)",
    qty: 2,
    mrp: 865,
    part: "TP",
  },
  {
    code: "ST-1376",
    name: "TP-SPLENDOR I-SMART TAIL BLACK FOR BLUE BIKE (TP :- Tail Panel)",
    qty: 2,
    mrp: 865,
    part: "TP",
  },
  {
    code: "ST-1377",
    name: "TP-SPLENDOR I-SMART TAIL BLACK FOR GREY BIKE (TP :- Tail Panel)",
    qty: 2,
    mrp: 865,
    part: "TP",
  },
  {
    code: "ST-1378",
    name: "TP-SPLENDOR I-SMART TAIL BLACK FOR GREEN BIKE (TP :- Tail Panel)",
    qty: 2,
    mrp: 865,
    part: "TP",
  },
  {
    code: "ST-1378-A",
    name: "TP-SPLENDOR I-SMART (BK-SILVER) (TP :- Tail Panel)",
    qty: 2,
    mrp: 865,
    part: "TP",
  },
  {
    code: "ST-1378-B",
    name: "TP-SPLENDOR I-SMART (BK-RED) (TP :- Tail Panel)",
    qty: 2,
    mrp: 865,
    part: "TP",
  },
  {
    code: "ST-1391",
    name: "TP-UNICORN O/M BLACK (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1392",
    name: "TP-UNICORN O/M RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1396",
    name: "TP-CB UNICORN BLACK (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1397",
    name: "TP-CB UNICORN RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1398",
    name: "TP-CB UNICORN S.RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1399",
    name: "TP-CB UNICORN SILVER (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1400",
    name: "TP-CB UNICORN GREY (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1414-E",
    name: "TP-SHINE T-2 (BK-BLUE) (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1414-F",
    name: "TP-SHINE T-2 (BK-RED) (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1405",
    name: "TP-SHINE T-3 (BK-RED) (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1406",
    name: "TP-SHINE T-3 (BK-GREY) (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1407",
    name: "TP-SHINE T-3 S.RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1408",
    name: "TP-SHINE T-3 BLUE (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1409",
    name: "TP-SHINE T-3 GREY (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1410",
    name: "TP-CB SHINE T-4 (BK-RED) (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1411",
    name: "TP-CB SHINE T-4 (BK-GREY) (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1412",
    name: "TP-CB SHINE T-4 W.RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1413",
    name: "TP-CB SHINE T-4 BLUE (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1414",
    name: "TP-CB SHINE T-4 GREY (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1401",
    name: "TP-CB SHINE T-4 & T-5 (BK-RED) (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1401-A",
    name: "TP-CB SHINE T-4 & T-5 (BK-GREY) (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1401-B",
    name: "TP-CB SHINE T-5 WHITE (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1402",
    name: "TP-CB SHINE T-4 & T-5 W.RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1403",
    name: "TP-CB SHINE T-4 & T-5 SILVER (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1404",
    name: "TP-CB SHINE T-4 & T-5 GENY GREY (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1404-A",
    name: "TP-CB SHINE T-4 & T-5 MANSOON GREY (TP :- Tail Panel)",
    qty: 2,
    mrp: 755,
    part: "TP",
  },
  {
    code: "ST-1404-B",
    name: "TP-CB SHINE T-6 DX (BK-RED) (TP :- Tail Panel)",
    qty: 2,
    mrp: 895,
    part: "TP",
  },
  {
    code: "ST-1404-C",
    name: "TP-CB SHINE T-6 DX RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 895,
    part: "TP",
  },
  {
    code: "ST-1404-D",
    name: "TP-CB SHINE T-6 DX W.RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 895,
    part: "TP",
  },
  {
    code: "ST-1404-E",
    name: "TP-CB SHINE T-6 DX GENY GREY (TP :- Tail Panel)",
    qty: 2,
    mrp: 895,
    part: "TP",
  },
  {
    code: "ST-1404-F",
    name: "TP-CB SHINE T-6 DX BLUE (TP :- Tail Panel)",
    qty: 2,
    mrp: 895,
    part: "TP",
  },
  {
    code: "ST-1404-H",
    name: "TP-CB SHINE T-6 DX S.RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 895,
    part: "TP",
  },
  {
    code: "ST-1404-I",
    name: "TP-CB SHINE T-6 DX BROWN (TP :- Tail Panel)",
    qty: 2,
    mrp: 895,
    part: "TP",
  },
  {
    code: "ST-1400-B",
    name: "TP-CB SHINE BS-6 (BK-RED) (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1400-D",
    name: "TP-CB SHINE BS-6 GREY (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1400-E",
    name: "TP-CB SHINE BS-6 BLUE (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1400-F",
    name: "TP-CB SHINE BS-6 RED (TP :- Tail Panel)",
    qty: 2,
    mrp: 1220,
    part: "TP",
  },
  {
    code: "ST-1400-H",
    name: "TP-CB SHINE SP MAT GREY (TP :- Tail Panel)",
    qty: 2,
    mrp: 1170,
    part: "TP",
  },
];
